test:
	coverage run -m unittest discover tests
	coverage html

test_date_time:
	python3 -m unittest tests.test_date_interval

test_relations:
	python3 -m unittest tests.test_relations

test_graph:
	python3 -m unittest tests.test_graph